version: 2
build:
  os: "ubuntu-22.04"
  commands:
    - curl -fsSL https://pixi.sh/install.sh | bash
    - chmod +x ~/.pixi/bin/pixi
    - ~/.pixi/bin/pixi run -e docs postinstall
    - ~/.pixi/bin/pixi run -e docs build-docs
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/_build/html/** $READTHEDOCS_OUTPUT/html/
