name: Nightly CI on onnx-weekly

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    paths:
      - ".github/workflows/nightly.yml"

defaults:
  run:
    shell: bash -el {0}

jobs:
  tests:
    name: "Linux - unit tests - ${{ matrix.OS }} - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: ${{ matrix.OS }}
    env:
      CI: True
    strategy:
      fail-fast: true
      matrix:
        OS: ["ubuntu-latest"]
        PYTHON_VERSION: ['3.12' ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: mamba-org/setup-micromamba@v1 
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.PYTHON_VERSION }}
      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pip install onnx-weekly --pre
          pip install .
          pytest
